#	Copyright (c) 1990, 1991, 1992 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#ident	"@(#)oampkg:common/cmd/oampkg/pkgaudit/Makefile	1.1"
#ident	"$Header: $"

include $(CMDRULES)

SRCBASE=../
OBJECTS=pkgaudit

all:	pkgaudit

pkgaudit: pkgaudit.sh
	cp pkgaudit.sh pkgaudit

clean:

clobber:	clean
	-rm -rf pkgaudit

lintit:

include $(SRCBASE)Install
