#	Copyright (c) 1987, 1988 Microsoft Corporation
#	  All Rights Reserved

#	This Module contains Proprietary Information of Microsoft
#	Corporation and should be treated as Confidential.

#ident	"@(#)adm:common/cmd/.adm/cshrc	1.4"

umask 022	# set default file creation mask

# calculate available disk space in root filesystem.
	echo ""		# skip a line
	/bin/sh /etc/dfspace

# issue message of the day
	echo ""		# skip a line
	if ( -r /etc/motd ) cat /etc/motd

# set default attributes for terminal
	stty erase '^h' echoe
	if ( $?LOGTTY == 0) set LOGTTY = `tty`

# check mailbox and news bulletins
	mail -e
	if ( $status == 0 ) echo "\nyou have mail"
	if ( $LOGNAME != root ) news -n

# set TERM on console

	if ( $?TERM == 0 ) then
		set term  = ansi
		if ( `expr "$LOGTTY" : '.*/\(.*\)'` == "console" ) then
			# check if it is an at386
			/usr/sbin/isat386
			if ( $status == 0 ) then
				# it is an at386, check for color
				/usr/sbin/adpt_type
				if ( $status == 3 ) then	# VGA color?
					set term = AT386	# color at386
				else
					set term = AT386-M	# default to monochrome
				endif
			endif
		endif
	endif

# set USER
	if ( $?LOGNAME != 0 ) set user = $LOGNAME

