/*	Copyright (c) 1990, 1991, 1992 UNIX System Laboratories, Inc.	*/
/*	Copyright (c) 1988, 1989, 1990 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF     	*/
/*	UNIX System Laboratories, Inc.                     	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ifndef NOIDENT
#ident	"@(#)dtmail:text.h	1.32"
#endif

#define BUT_READ_PROP		"dtmail:2" FS "Reader Properties..."
#define BUT_SEND_PROP		"dtmail:3" FS "Sender Properties..."
#define BUT_EXIT		"dtmail:4" FS "Exit"

#define BUT_MANAGE_MAIL_DDD	"dtmail:10" FS "Manager..."
#define BUT_READ_MAIL_DDD	"dtmail:11" FS "Reader..."
#define BUT_SEND_MAIL_DDD	"dtmail:12" FS "Sender..."
#define BUT_ALIAS_MNG_DDD	"dtmail:13" FS "Alias Manager..."

#define BUT_MAIL_DDD		"dtmail:20" FS "Mail..."
#define BUT_TOC_DDD		"dtmail:21" FS "Table of Contents..."
#define BUT_HELP_DESK_DDD	"dtmail:22" FS "Help Desk..."
#define BUT_MANAGER_DDD		"dtmail:23" FS "Mail Manager..."
#define BUT_READER_DDD		"dtmail:24" FS "Mail Reader..."
#define BUT_SENDER_DDD		"dtmail:25" FS "Mail Sender..."
#define BUT_ALIAS_DDD		"dtmail:26" FS "Alias Manager..."

#define BUT_FILE		"dtmail:30" FS "File"
#define BUT_EDIT		"dtmail:31" FS "Edit"
#define BUT_VIEW		"dtmail:32" FS "View"
#define BUT_MAIL		"dtmail:33" FS "Mail"
#define BUT_HELP		"dtmail:34" FS "Help"
#define BUT_MESS		"dtmail:35" FS "Message"

#define BUT_OPEN		"dtmail:40" FS "Open"
#define BUT_OPEN_DDD		"dtmail:41" FS "Open..."
#define BUT_SAVE_MESSAGE	"dtmail:42" FS "Save Message"
#define BUT_SAVE_MESSAGE_AS_DDD	"dtmail:43" FS "Save Message To ..."
#define BUT_PRINT		"dtmail:44" FS "Print"
#define BUT_SAVE_MESSAGES	"dtmail:45" FS "Save Message(s)"
#define BUT_SAVE_MESSAGES_AS_DDD	"dtmail:46" FS "Save Message(s) To ..."

#define BUT_UNDO		"dtmail:50" FS "Undo"
#define BUT_CUT			"dtmail:51" FS "Cut"
#define BUT_COPY		"dtmail:52" FS "Copy"
#define BUT_PASTE		"dtmail:53" FS "Paste"
#define BUT_DELETE		"dtmail:54" FS "Delete"
#define BUT_SELECT_ALL		"dtmail:55" FS "Select All"
#define BUT_UNSELECT_ALL	"dtmail:56" FS "Unselect All"
#define BUT_UNDELETE_DDD	"dtmail:57" FS "Undelete..."

#define BUT_MAIL_MANAGER_DDD	"dtmail:60" FS "Mail Manager"
#define BUT_READ_DDD		"dtmail:61" FS "Reader..."
#define BUT_MAILER_DDD		"dtmail:62" FS "Sender..."
#define BUT_REPLY_SENDER_DDD	"dtmail:63" FS "Reply to Sender..."
#define BUT_REPLY_SENDER_ATT_DDD "dtmail:64" FS "Reply to Sender (Att.)..."
#define BUT_REPLY_ALL_DDD	"dtmail:65" FS "Reply to All..."
#define BUT_REPLY_ALL_ATT_DDD	"dtmail:66" FS "Reply to All (Att.)..."
#define BUT_FORWARD_DDD		"dtmail:67" FS "Forward..."

#define BUT_NEXT		"dtmail:70" FS "Next"
#define BUT_PREV		"dtmail:71" FS "Prev"

#define BUT_UNDELETE		"dtmail:80" FS "Undelete"
#define BUT_SAVE		"dtmail:81" FS "Save"
#define BUT_INCLUDE		"dtmail:82" FS "Include"
#define BUT_SAVE_AS_DDD		"dtmail:83" FS "Save As..."

#define BUT_NEW			"dtmail:90" FS "New"
#define BUT_ADD			"dtmail:91" FS "Add"

#define BUT_OVERWRITE		"dtmail:110" FS "Overwrite"
#define BUT_ALIASES_DDD		"dtmail:112" FS "Aliases..."

#define BUT_BRIEF		"dtmail:120" FS "Brief"
#define BUT_FULL		"dtmail:121" FS "Full"

#define BUT_OK			"dtmail:130" FS " OK "
#define BUT_CANCEL		"dtmail:131" FS "Cancel"
#define BUT_SEND		"dtmail:132" FS "Send"
#define BUT_APPLY		"dtmail:133" FS "Apply"
#define BUT_RESET		"dtmail:134" FS "Reset"
#define BUT_SHOW		"dtmail:135" FS "Show Errors"

#define BUT_ON			"dtmail:140" FS "On"
#define BUT_OFF			"dtmail:141" FS "Off"

#define TXT_TO			"dtmail:150" FS "To:"
#define TXT_SUBJECT		"dtmail:151" FS "Subject:"
#define TXT_CC			"dtmail:152" FS "Cc:"
#define TXT_BCC			"dtmail:153" FS "Bcc:"
#define TXT_NAMES		"dtmail:154" FS "Names:"

#define TXT_MAIL_MNG_DELETE	"dtmail:160" FS "Mail Manager: Undelete"
#define TXT_DOTML		"dtmail:161" FS ".ml"
#define TXT_DOT_MAILRC		"dtmail:162" FS ".mailrc"
#define TXT_SYSTEM_MAILRC	"dtmail:163" FS "/usr/lib/mailx/mailx.rc"
#define TXT_MNG_ALREADY_ACTIVE	"dtmail:164" FS "Already have a Mail Manager displaying this file"
#define TXT_FILE_ALREADY_OPEN	"dtmail:165" FS "Mail file (%s) is already open."

#define TXT_TOO_LARGE		"dtmail:170" FS "File too large to read"
#define TXT_CANT_OPEN		"dtmail:171" FS "Cannot open file: "
#define TXT_INVALID_SELECTION	"dtmail:172" FS "Invalid selection"
#define TXT_INVALID_TARGET	"dtmail:173" FS "Messages can only be dropped on mail files (*.ml)"
#define TXT_INVALID_FILENAME	"dtmail:174" FS "File name is invalid."

#define TXT_MAILRC_ENV		"dtmail:180" FS "MAILRC"
#define TXT_FORWARD		"dtmail:183" FS "Your mail is being forwarded"
#define CANT_READ_MF_OPEN	"dtmail:184" FS "Cannot read mail file: it's already being read"
#define TXT_EMPTY_FILE		"dtmail:185" FS "Empty file"
#define TXT_CANT_BE_OPENED	"dtmail:186" FS "Mail file %s cannot be opened - %s"
#define TXT_FILE_DOESNT_EXIST	"dtmail:187" FS "Mail file %s cannot be opened - file does not exist"
#define TXT_NO_MORE_MESSAGES	"dtmail:188" FS "No more messages in mail file %s"

#define TXT_CANT_SAVE_FILE	"dtmail:190" FS "Could not save in %s - %s"
#define TXT_MESSAGE_SAVED	"dtmail:191" FS "Message(s) saved to %s"
#define TXT_NEW_MAIL		"dtmail:192" FS "You have new mail in %s"
#define TXT_E_MAIL_COLON	"dtmail:193" FS "Mail"

#define TXT_MANAGE_RIGHT_FOOTER	"dtmail:200" FS "%d Messages, %d New, %d Unread"
#define TXT_FIRST_HALF_HEADER	"dtmail:201" FS "   No Status From               "
#define TXT_SECOND_HALF_HEADER	"dtmail:202" FS "Date     Time    Size       Subject                  "
#define TXT_ELECTRONIC_MAIL	"dtmail:203" FS "Mail Manager %s"
#define TXT_E_MAIL_ICON_NAME	"dtmail:204" FS "Mail"
#define TXT_PRINTED_MSGS	"dtmail:205" FS "Selected messages have been sent to the default printer"
#define TXT_PRINTED_MSG		"dtmail:206" FS "Message has been sent to the default printer"
#define TXT_NO_MAIL		"dtmail:207" FS "No mail"
#define TXT_PRINT_FAILED	"dtmail:208" FS "Print failed"

#define TXT_NOT_SENT		"dtmail:210" FS "Message has not been sent.  Exit Sender anyway?"
#define TXT_NEW_TEXT		"dtmail:211" FS "Message has not been sent.  Clear window anyway?"
#define TXT_RU_SURE		"dtmail:212" FS "Exit all Mail windows.  Are you sure?"
#define TXT_OPEN_OUTGOING	"dtmail:213" FS "Mail Sender: Open Saved Message"
#define TXT_SAVE_OUTGOING	"dtmail:214" FS "Mail Sender: Save Outgoing Message"
#define TXT_SAVE_MANAGE_MAIL	"dtmail:215" FS "Mail Manager: Save Mail Messages"
#define TXT_SAVE_READ_MAIL	"dtmail:216" FS "Mail Reader: Save Mail Message"
#define TXT_FILE_OVERWRITE	"dtmail:218" FS "File already exists.  Overwrite it?"

#define TXT_OPEN_MANAGER_FILE	"dtmail:224" FS "Mail Manager: Open Mail File"
#define TXT_STAR_DOT_ML		"dtmail:225" FS "*.ml"
#define TXT_OPEN_READ_FILE	"dtmail:226" FS "Mail Reader: Open Mail File"
#define TXT_NO_CHANGE		"dtmail:228" FS "This mail message has already been sent.  Send it again?"
#define TXT_TRANS_ERROR		"dtmail:229" FS "Mail may not have been sent due to invalid address"

#define TXT_AT_FIRST		"dtmail:230" FS "Already at first message."
#define TXT_AT_LAST		"dtmail:231" FS "Already at last message."
#define TXT_EMAIL_READER	"dtmail:232" FS "Mail Reader"
#define TXT_MANAGER_ACTIVE	"dtmail:233" FS "Already have a Mail Manager displaying this file"
#define TXT_BINARY_TEXT		"dtmail:234" FS "Cannot display message.  It contains binary data."
#define TXT_NO_ITEM		"dtmail:235" FS "No message selected"
#define TXT_MESSAGE_SENT	"dtmail:236" FS "Message has been sent"
#define TXT_INVALID_ADDRESS	"dtmail:237" FS "Mail contains invalid addresses:"
#define TXT_COMPOSE		"dtmail:239" FS "Mail Sender: Create Message"

#define TXT_HEADER_COLON	"dtmail:240" FS "Header:"
#define TXT_BRIEF_HEADER	"dtmail:241" FS "Brief Header Shows:"
#define TXT_PROP_READER		"dtmail:242" FS "Mail Reader Properties"
#define TXT_REPLY_TO		"dtmail:243" FS "Mail Sender: Reply to message from %s"
#define TXT_FORWARD_FROM	"dtmail:244" FS "Mail Sender: Forwarding message from %s"
#define TXT_SAVED_IN		"dtmail:245" FS "Saved message in %s"
#define TXT_SEND_PRINTED	"dtmail:246" FS "Message sent to the default printer"
#define TXT_NOT_A_SAVE_FILE	"dtmail:247" FS "Cannot open %s: file does not contain a \"Saved\" message."
#define TXT_JUST_MAIL		"dtmail:248" FS "Mail"
#define TXT_NOT_A_MAIL_FILE	"dtmail:249" FS "Cannot open %s: not a mail file"

#define TXT_RECORD_OUTGOING	"dtmail:250" FS "Save copy of outgoing mail:"
#define TXT_SIGNATURE		"dtmail:251" FS "Signature:"
#define TXT_MAIL_PROPERTIES	"dtmail:252" FS "Mail Sender Properties"
#define TXT_OUT_GOING		"dtmail:253" FS "Mail Sender: Outgoing Message"
#define TXT_SENDER_ICON_NAME	"dtmail:254" FS "Sender"
#define TXT_MANAGER_ICON_NAME	"dtmail:255" FS "Manager"
#define TXT_READER_ICON_NAME	"dtmail:256" FS "Reader"

#define TXT_ALIAS_HEAD_1	"dtmail:260" FS "  Name                             "
#define TXT_ALIAS_HEAD_2	"dtmail:261" FS "  Mail Addresses                                             "
#define TXT_NAME_COLON		"dtmail:262" FS "Name:"
#define TXT_ADDRESS_COLON	"dtmail:263" FS "Address:"
#define TXT_ALIAS_MANAGER	"dtmail:264" FS "Mail Alias Manager"
#define TXT_ALIAS_MANAGER_ICON	"dtmail:265" FS "Alias Mgr"
#define TXT_OVERWRITE_ALIAS	"dtmail:266" FS "Alias name already in use.	 Overwrite it?"
#define TXT_MUST_BE_A_NAME	"dtmail:267" FS "You have not entered the name of a new or existing Alias."
#define TXT_MUST_BE_AN_ADDRESS	"dtmail:268" FS "You have not entered an Address."

#define TXT_ILLEGAL_CHARACTER	"dtmail:270" FS "\"Name\" may only contain letters and numbers."
#define TXT_NO_CHANGE_NAME	"dtmail:272" FS "You did not make any changes."
#define TXT_DOT_ALIAS		"dtmail:273" FS "/tmp/.ALIAS%-d"
#define TXT_CANT_OPEN_4_PRINT	"dtmail:274" FS "Could not open file for printing"
#define TXT_ALIAS_2_PRINTER	"dtmail:276" FS "Alias list sent to default printer."
#define TXT_FILE_WAS_SPOOLED	"dtmail:277" FS "File sent to printer."
#define TXT_PRINT_CANCELED	"dtmail:278" FS "Print request cancelled."

#define TXT_COULDNT_B_PRINTED	"dtmail:280" FS "File could not be printed."
#define TXT_PRINTER_NA		"dtmail:281" FS "Printer not available."
#define TXT_PRINT_TITLE		"dtmail:283" FS "                           Alias List"
#define TXT_TITLE_NAME		"dtmail:284" FS "Name"
#define TXT_TITLE_ADDR		"dtmail:285" FS "Mail Address or Translation"

#define TXT_MAILRC_UNREADABLE	"dtmail:290" FS "Unreadable .mailrc file"
#define TXT_MAILRC_WRITTEN	"dtmail:291" FS "Aliases saved."
#define TXT_E_MAIL_UNDELETE	"dtmail:292" FS "Mail Alias Manager: Undelete"
#define TXT_E_MAIL_ALIASES	"dtmail:293" FS "Mail Aliases"
#define TXT_R_U_SURE		"dtmail:294" FS "You have unsaved Alias changes.  Are you sure you want to exit?"
#define TXT_ONLY_ONE_FILE	"dtmail:300" FS "You can only drop one file on this window"
#define TXT_LUCY_BOLD		"dtmail:301" FS "-*-lucidatypewriter-bold-r-*-*-*-*-*-*-*-*-iso8859-1"
#define TXT_LUCY_MEDIUM		"dtmail:302" FS "-*-lucidatypewriter-medium-r-*-*-*-*-*-*-*-*-iso8859-1"
#define TXT_LIMITS_EXCEEDED	"dtmail:303" FS "Warning: Only the first %d messages can be displayed"
#define TXT_DELETE_LM_EXCEEDED	"dtmail:304" FS "Warning: Only the first %d deleted messages can be displayed"

#define HELP_MAIL_TITLE			"dtmail:350" FS "The Mail Application"
#define HELP_MAIL_SECT			"20"
#define HELP_MANAGER_TITLE		"dtmail:351" FS "Manager"
#define HELP_MANAGER_SECT		"300"
#define HELP_READER_TITLE		"dtmail:352" FS "Reader Window"
#define HELP_READER_SECT		"630"
#define HELP_SENDER_TITLE		"dtmail:353" FS "Sender Window"
#define HELP_SENDER_SECT		"900"
#define HELP_ALIAS_MANAGER_TITLE	"dtmail:354" FS "Alias Manager Window"
#define HELP_ALIAS_MANAGER_SECT		"1200"

#define HELP_TOC_TITLE			"dtmail:355" FS "Table of Contents"
#define HELP_TOC_SECT			"TOC"
#define HELP_DESK_TITLE			"dtmail:356" FS "Help Desk"
#define HELP_DESK_SECT			"HelpDesk"

#define HELP_MANAGER_OPEN_TITLE		"dtmail:357" FS "Mail Manager: Open Mail File Window"
#define HELP_MANAGER_OPEN_SECT		"320"
#define HELP_MANAGER_SAVEAS_TITLE	"dtmail:358" FS "Mail Manager: Save Mail Messages Window"
#define HELP_MANAGER_SAVEAS_SECT	"340"
#define HELP_MANAGER_UNDELETE_TITLE	"dtmail:359" FS "Mail Manager: Undelete Mail Messages Window"
#define HELP_MANAGER_UNDELETE_SECT	"400"

#define HELP_READER_OPEN_TITLE		"dtmail:360" FS "Mail Reader: Open Read Mail Messages Window"
#define HELP_READER_OPEN_SECT		"550"
#define HELP_READER_SAVE_TITLE		"dtmail:361" FS "Mail Reader: Save Read Mail Messages Window"
#define HELP_READER_SAVE_SECT		"590"

#define HELP_SENDER_OPEN_TITLE		"dtmail:362" FS "Mail Sender: Open Outgoing Mail Messages Window"
#define HELP_SENDER_OPEN_SECT		"1160"
#define HELP_SENDER_SAVE_TITLE		"dtmail:363" FS "Mail Sender: Save Outgoing Mail Messages Window"
#define HELP_SENDER_SAVE_SECT		"1160"

#define HELP_READPROP_TITLE		"dtmail:364" FS "Mail Read Properties Window"
#define HELP_READPROP_SECT		"200"
#define HELP_SENDPROP_TITLE		"dtmail:365" FS "Mail Send Properties Window"
#define HELP_SENDPROP_SECT		"250"

#define HELP_ALIASES_TITLE		"dtmail:366" FS "Mail Aliases Window"
#define HELP_ALIASES_SECT		"1110"

#define HELP_ALIAS_MANAGER_UNDELETE_TITLE "dtmail:367" FS "Mail Alias Manager Undelete Window"
#define HELP_ALIAS_MANAGER_UNDELETE_SECT  "1320"
#define HELP_ALIAS_MANAGER_OVERWRITE_TITLE "dtmail:368" FS "Mail Alias Manager Overwrite Window"
#define HELP_ALIAS_MANAGER_OVERWRITE_SECT  "1330"
#define HELP_ALIAS_MANAGER_SURE_TITLE "dtmail:369" FS "Mail Alias Manager Check Exit Window"
#define HELP_ALIAS_MANAGER_SURE_SECT  "1330"

#define MNEM_ALIASES_DDD		"dtmail:501" FS "A"
#define MNEM_ALIAS_DDD			"dtmail:502" FS "A"
#define MNEM_ALIAS_MNG_DDD		"dtmail:503" FS "A"
#define MNEM_APPLY			"dtmail:504" FS "A"
#define MNEM_BRIEF			"dtmail:505" FS "B"
#define MNEM_CANCEL			"dtmail:506" FS "C"
#define MNEM_COPY			"dtmail:507" FS "C"
#define MNEM_CUT			"dtmail:508" FS "t"
#define MNEM_DELETE			"dtmail:509" FS "D"
#define MNEM_EDIT			"dtmail:510" FS "E"
#define MNEM_EXIT_E			"dtmail:511" FS "X"
#define MNEM_EXIT_X			"dtmail:512" FS "X"
#define MNEM_FILE			"dtmail:513" FS "F"
#define MNEM_FORWARD_DDD		"dtmail:514" FS "F"
#define MNEM_FULL			"dtmail:515" FS "F"
#define MNEM_HELP			"dtmail:516" FS "H"
#define MNEM_HELP_DESK_DDD		"dtmail:517" FS "D"
#define MNEM_INCLUDE			"dtmail:518" FS "I"
#define MNEM_MAIL			"dtmail:519" FS "M"
#define MNEM_MAILER_DDD			"dtmail:520" FS "S"
#define MNEM_MAIL_DDD			"dtmail:521" FS "M"
#define MNEM_MAIL_MANAGER_DDD		"dtmail:522" FS "M"
#define MNEM_MANAGER_DDD		"dtmail:523" FS "M"
#define MNEM_MANAGE_MAIL_DDD		"dtmail:524" FS "M"
#define MNEM_MESS			"dtmail:525" FS "M"
#define MNEM_NEW			"dtmail:526" FS "N"
#define MNEM_NEXT			"dtmail:527" FS "N"
#define MNEM_OFF			"dtmail:528" FS "f"
#define MNEM_OK				"dtmail:529" FS "O"
#define MNEM_ON				"dtmail:530" FS "O"
#define MNEM_OPEN			"dtmail:531" FS "O"
#define MNEM_OPEN_DDD			"dtmail:532" FS "O"
#define MNEM_OVERWRITE			"dtmail:533" FS "O"
#define MNEM_PASTE			"dtmail:534" FS "P"
#define MNEM_PREV			"dtmail:535" FS "P"
#define MNEM_PRINT			"dtmail:536" FS "P"
#define MNEM_READER_DDD			"dtmail:537" FS "R"
#define MNEM_READ_DDD			"dtmail:538" FS "R"
#define MNEM_READ_MAIL_DDD		"dtmail:539" FS "R"
#define MNEM_READ_PROP			"dtmail:540" FS "R"
#define MNEM_REPLY_ALL_ATT_DDD		"dtmail:541" FS "l"
#define MNEM_REPLY_ALL_DDD		"dtmail:542" FS "A"
#define MNEM_REPLY_SENDER_ATT_DDD	"dtmail:543" FS "t"
#define MNEM_REPLY_SENDER_DDD		"dtmail:544" FS "p"
#define MNEM_RESET			"dtmail:545" FS "R"
#define MNEM_SAVE			"dtmail:546" FS "S"
#define MNEM_SAVE_AS_DDD		"dtmail:547" FS "A"
#define MNEM_SAVE_MESSAGE		"dtmail:548" FS "S"
#define MNEM_SAVE_MESSAGES		"dtmail:549" FS "S"
#define MNEM_SAVE_MESSAGES_AS_DDD	"dtmail:550" FS "A"
#define MNEM_SAVE_MESSAGE_AS_DDD	"dtmail:551" FS "A"
#define MNEM_SELECT_ALL			"dtmail:552" FS "S"
#define MNEM_SEND			"dtmail:553" FS "S"
#define MNEM_SENDER_DDD			"dtmail:554" FS "S"
#define MNEM_SEND_MAIL_DDD		"dtmail:555" FS "S"
#define MNEM_SEND_PROP_S		"dtmail:556" FS "S"
#define MNEM_SEND_PROP_t		"dtmail:557" FS "t"
#define MNEM_TOC_DDD			"dtmail:558" FS "T"
#define MNEM_UNDELETE			"dtmail:559" FS "U"
#define MNEM_UNDELETE_DDD_L		"dtmail:560" FS "L"
#define MNEM_UNDELETE_DDD_N		"dtmail:561" FS "N"
#define MNEM_UNDO			"dtmail:562" FS "U"
#define MNEM_UNSELECT_ALL		"dtmail:563" FS "A"
#define MNEM_VIEW			"dtmail:564" FS "V"
#define MNEM_SHOW			"dtmail:565" FS "S"
