.\"ident	"@(#)r5plaid:plaid.man	1.1"
.TH PLAID 1 "Release 4" "X Version 11"
.SH NAME
plaid \- paint some plaid-like patterns in an X window
.SH SYNOPSIS
.B plaid
[-option ...]
.SH OPTIONS
.TP 8
.B \-b
enable backing store for the window
.TP 8
.B \-fg \fIcolor\fP
This option specifies the color to use for the foreground of the window.  
The default is ``white.''
.TP 8
.B \-bg \fIcolor\fP
This option specifies the color to use for the background of the window.  
The default is ``black.''
.TP 8
.B \-bd \fIcolor\fP
This option specifies the color to use for the border of the window.
The default is ``white.''
.TP 8
.B \-bw \fInumber\fP
This option specifies the width in pixels of the border surrounding the window.
.TP 8
.B \-geometry \fIgeometry\fB
define the initial window geometry; see \fIX(1)\fP.
.TP 8
.B \-display \fIdisplay\fB
specify the display to use; see \fIX(1)\fP.
.SH DESCRIPTION
.I Plaid
displays a continually changing plaid-like pattern in a window.
.SH "SEE ALSO"
X(1)
.SH BUGS
There are no known bugs.  There are lots of lacking features.
.SH COPYRIGHT
Copyright 1988, Massachusetts Institute of Technology.
.br
See \fIX(1)\fP for a full statement of rights and permissions.

