#	Copyright (c) 1990, 1991, 1992 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#	Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#	Portions Copyright(c) 1988, Sun Microsystems, Inc.
#	All Rights Reserved.

#ident	"@(#)compress:compress.mk	1.6.5.1"
#ident "$Header: compress.mk 1.2 91/03/22 $"

#	Makefile for compress

include $(CMDRULES)

INSDIR = $(USRBIN)
OWN = bin
GRP = bin

#top#
# Generated by makefile 1.47

MAKEFILE = compress.mk

MAINS = compress uncompress zcat

OBJECTS =  compress.o

SOURCES =  compress.c

all:		$(MAINS)

compress: compress.o 
	$(CC) $(CFLAGS) $(DEFLIST) -o compress compress.o $(LDFLAGS) $(LDLIBS) \
		$(SHLIBS)

uncompress:	compress
		rm -f uncompress
		ln compress uncompress

zcat:		compress
		rm -f zcat
		ln compress zcat

compress.o:	 $(INC)/signal.h $(INC)/stdio.h \
		 $(INC)/ctype.h $(INC)/sys/types.h \
		 $(INC)/sys/stat.h $(INC)/sys/ioctl.h \
		 $(INC)/unistd.h

GLOBALINCS = $(INC)/signal.h $(INC)/stdio.h $(INC)/ctype.h \
	$(INC)/types.h $(INC)/sys/stat.h $(INC)/sys/ioctl.h \
		 $(INC)/unistd.h

clean:
	rm -f $(OBJECTS)

clobber: clean
	rm -f $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

install: all
	$(INS) -f $(INSDIR) -m 0555 -u bin -g bin compress
	rm -f $(INSDIR)/uncompress $(INSDIR)/zcat
	ln $(INSDIR)/compress $(INSDIR)/uncompress
	ln $(INSDIR)/compress $(INSDIR)/zcat

size: all
	$(SIZE) $(MAINS)

strip: all
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(INSDIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(INSDIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
