/*	Copyright (c) 1990, 1991, 1992 UNIX System Laboratories, Inc.	*/
/*	Copyright (c) 1988, 1989, 1990 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF     	*/
/*	UNIX System Laboratories, Inc.                     	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ifndef NOIDENT
#pragma ident	"@(#)dtadmin:userad/login_msgs.h	1.20"
#endif
/*
 * This file contains all the message strings for the Desktop UNIX
 * dtadmin client dtuser.
 * 
 */

#define	string_appName 	"dtuser:1" FS "User Setup"
#define	string_iconName "dtuser:2" FS "User Setup"
#define	string_badGroup "dtuser:3" FS "Nonexistent group; select another\n\n"
#define	string_badShell	"dtuser:4" FS "Shell not executable by user:  "
#define	string_malloc	"dtuser:5" FS "Operation failed due to lack of memory"
#define	string_permfile	"dtuser:6" FS "Unable to read permissions table"
#define	string_adm	"dtuser:7" FS "Unable to add user to admin database"
#define	string_noChange	"dtuser:8" FS "User account %s was left unchanged"
#define	string_propLine	"dtuser:9" FS "User Setup: User Account Properties"
#define	string_sysLine	"dtuser:10" FS "User Setup: Reserved Account Properties"
#define	string_groupLine	"dtuser:11" FS "User Setup: Group Properties"
#define	string_addUserLine	"dtuser:12" FS "User Setup: Add New User Account"
#define	string_addSysLine	"dtuser:13" FS "User Setup: Add New Reserved Account"
#define	string_addGroupLine	"dtuser:14" FS "User Setup: Add New Group"
#define	string_permLine	"dtuser:15" FS "User Setup: User Permissions"
#define	string_errLine	"dtuser:16" FS "User Setup: Error"
#define	string_confLine	"dtuser:17" FS "User Setup: Confirmation"
#define	string_userBaseLine	"dtuser:18" FS "User Setup: User Accounts"
#define	string_sysBaseLine	"dtuser:19" FS "User Setup: Reserved Accounts"
#define	string_groupBaseLine	"dtuser:20" FS "User Setup: Groups"

#define	string_noPerms	"dtuser:21" FS "you are not authorized to %s %ss"
#define	string_inUse	"dtuser:22" FS "cannot %s %s %s while in use"
#define	string_dupl	"dtuser:23" FS "%s would duplicate an existing %s"
#define	string_badDir	"dtuser:24" FS "cannot %s home directory for %s %s"
#define	string_unknown	"dtuser:25" FS "%s %s %s: unrecognized error"
#define	string_shellRequired	"dtuser:26" FS "Please fill in the \"Shell\" field"
#define	string_deleteFiles	"dtuser:27" FS "Permamently delete all files and folders in %s?  Are you sure?"
#define	string_backupErrs	"dtuser:28" FS "Errors occured while backing up %s's files. Do you still want to permamently delete all files and folders in %s?"
#define	string_notBackedUp	"dtuser:29" FS "%s's files were not backed up.  Do you still want to permamently delete all files and folders in %s?"

#define	format_noSelectFmt	"dtuser:31" FS "no %s has been selected"
#define	format_applyFmt		"dtuser:32" FS "%s %s %s %s"
#define	format_syntaxFmt	"dtuser:33" FS "invalid character '%c' in %s %s\n\n"
#define	format_noIdFmt	 	"dtuser:34" FS "%s field required\n\n"
#define	format_maxIdFmt	 	"dtuser:35" FS "%s must not be larger than %d\n\n"
#define	format_reuseFmt		"dtuser:36" FS "\n\n(Reuse existing %s %d?)"
#define	format_permFmt		"dtuser:37" FS "permission change for user %s%s"
#define	format_ownerFmt		"dtuser:38" FS "%s %s %s %s%s"
#define	format_ageIdFmt	 	"dtuser:39" FS "%s %s was previously used. You may not re-use it yet. It has not \"aged\" long enough.\n\n"
#define	format_inUse	 	"dtuser:40" FS "%s %s already in use; choose another\n\n"

#define	label_edit		"dtuser:41" FS "Account"
#define	label_view		"dtuser:42" FS "View"
#define	label_help		"dtuser:43" FS "Help"
#define	label_new		"dtuser:44" FS "New"
#define	label_delete		"dtuser:45" FS "Delete"
#define	label_users		"dtuser:46" FS "Users"
#define	label_sysaccts		"dtuser:47" FS "Reserved"
#define	label_groups		"dtuser:48" FS "Groups"
#define	label_glist		"dtuser:49" FS "Select Group From:"
#define	label_apply		"dtuser:50" FS "Apply"
#define	label_reset		"dtuser:51" FS "Reset"
#define	label_cancel		"dtuser:52" FS "Cancel"
#define	label_prop		"dtuser:53" FS "Properties..."
#define	label_perm		"dtuser:54" FS "Permissions..."
#define	label_yes		"dtuser:55" FS "Yes"
#define	label_no		"dtuser:56" FS "No"
#define	label_OK		"dtuser:57" FS "Continue"
#define	label_desktop		"dtuser:58" FS "Desktop"
#define	label_nondesk		"dtuser:59" FS "Nondesktop"
#define	label_ol		"dtuser:60" FS "OPEN LOOK"
#define	label_motif		"dtuser:61" FS "MOTIF"
#define	label_remove		"dtuser:62" FS "Remove User's Files:"
#define	label_bkup		"dtuser:63" FS "Backup User's Files:"

#define	label_login		"dtuser:64" FS "Login ID:"
#define	label_desc		"dtuser:65" FS "Comment:"
#define	label_uid		"dtuser:66" FS "       User ID:"
#define	label_home		"dtuser:67" FS "       Home Folder:"
#define	label_shell		"dtuser:68" FS "       Shell:"
#define	label_group		"dtuser:69" FS "Group:"
#define	label_gname		"dtuser:70" FS "Group Name:"
#define	label_gid		"dtuser:71" FS "Group ID Number:"
#define	label_type		"dtuser:72" FS "Type:"
#define	label_GUI		"dtuser:73" FS "GUI:"
#define	label_extra		"dtuser:74" FS "Extended Options:"
#define	label_remote		"dtuser:75" FS "       X-terminal Name:"
#define	label_owner_acct	"dtuser:76" FS "Selected User is the System Owner"
#define label_add		"dtuser:77" FS "Add"
#define label_user_may		"dtuser:78" FS "Selected User May:"

#define	mnemonic_edit		"dtuser:80" FS "t"
#define	mnemonic_view		"dtuser:81" FS "V"
#define	mnemonic_help		"dtuser:82" FS "H"
#define	mnemonic_new		"dtuser:83" FS "N"
#define	mnemonic_delete		"dtuser:84" FS "D"
#define	mnemonic_users		"dtuser:85" FS "U"
#define	mnemonic_sysaccts	"dtuser:86" FS "D"
#define	mnemonic_groups		"dtuser:87" FS "G"
#define	mnemonic_glist		"dtuser:88" FS "F"
#define	mnemonic_apply		"dtuser:89" FS "A"
#define	mnemonic_reset		"dtuser:90" FS "R"
#define	mnemonic_cancel		"dtuser:91" FS "C"
#define	mnemonic_prop		"dtuser:92" FS "P"
#define	mnemonic_perm		"dtuser:93" FS "P"
#define	mnemonic_desktop	"dtuser:94" FS "K"
#define	mnemonic_nondesk	"dtuser:95" FS "N"
#define	mnemonic_yes		"dtuser:96" FS "Y"
#define	mnemonic_no		"dtuser:97" FS "N"
#define	mnemonic_OK		"dtuser:98" FS "C"
#define	mnemonic_ol		"dtuser:99" FS "O"
#define	mnemonic_motif		"dtuser:100" FS "M"
#define	mnemonic_remove		"dtuser:101" FS "E"
#define	mnemonic_bkup		"dtuser:102" FS "B"
#define	mnemonic_owner_acct	"dtuser:103" FS "O"
#define	mnemonic_add		"dtuser:104" FS "A"
#define	mnemonic_action		"dtuser:105" FS "A"
#define	mnemonic_exit		"dtuser:106" FS "X"
#define	mnemonic_groupBtn	"dtuser:107" FS "G"

#define	label_action		"dtuser:121" FS "Actions"
#define	label_exit		"dtuser:122" FS "Exit"
#define	label_groupBtn		"dtuser:123" FS "Group"


#define	tag_addOp	"dtuser:150" FS "create"
#define	tag_chgOp	"dtuser:151" FS "modify"
#define	tag_delOp	"dtuser:152" FS "delete"
#define	tag_login	"dtuser:153" FS "user account"
#define	tag_desktop	"dtuser:154" FS "desktop environment"
#define	tag_group	"dtuser:155" FS "group"
#define	tag_good	"dtuser:156" FS " - succeeded"
#define	tag_bad		"dtuser:157" FS " - failed"
#define	tag_null	"dtuser:158" FS " - unchanged"
#define	tag_xferOp	"dtuser:159" FS "ownership"
#define	tag_query	"dtuser:160" FS "?"
#define tag_sys		"dtuser:161" FS "reserved account"   
#define tag_account	"dtuser:162" FS "user or reserved account"   

/* Help */

#define	label_intro		"dtuser:200" FS "User Setup..."
#define	label_toc		"dtuser:201" FS "Table of Contents..."
#define	label_hlpdsk		"dtuser:202" FS "Help Desk..."

#define	mnemonic_intro		"dtuser:205" FS "U"
#define	mnemonic_toc		"dtuser:206" FS "T"
#define	mnemonic_hlpdsk		"dtuser:207" FS "K"

#define	help_intro		"10"
#define	help_props		"230"
#define	help_groups		"280"
#define	help_perms		"180"
