/*	Copyright (c) 1990, 1991, 1992 UNIX System Laboratories, Inc.	*/
/*	Copyright (c) 1988, 1989, 1990 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF     	*/
/*	UNIX System Laboratories, Inc.                     	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ifndef	NOIDENT
#ident	"@(#)dtadmin:dialup/error.h	1.29"
#endif

#ifndef __Ol_Dialup_Error_h__
#define __Ol_Dialup_Error_h__
#include <Gizmos.h>

#define	HELP_FILE		"dtadmin/DialMgr.hlp"

#define GGT GetGizmoText
#define SET_HELP(id)		(id.title = GGT(id.title),\
				id.section = id.section?GGT(id.section):0)
#define SET_LABEL(id,n,name)    id[n].label = (XtArgVal)GGT(label##_##name);\
                                id[n].mnemonic = (XtArgVal)*GGT(mnemonic##_##name);

#define	format_usage		"DialupMgr:001" FS "Usage: %s [filename]"

#define	string_appName		"DialupMgr:101" FS "Dialup Setup"
#define	string_badName		"DialupMgr:102" FS "Invalid System Name."
#define	string_badPhone		"DialupMgr:103" FS "Invalid Phone Number."
#define	string_blankName	"DialupMgr:104" FS "You must provide a System Name!"
#define	string_noLogin		"DialupMgr:105" FS "Cannot determine who you are!"
#define	string_noPublic		"DialupMgr:106" FS "'/var/spool/uucppublic' does not exist!"
#define	string_noAccessPublic	"DialupMgr:107" FS "'/var/spool/uucppublic' has wrong permissions!"
#define	string_noCreatePublic	"DialupMgr:108" FS "Cannot create folder under '/var/spool/uucppublic'!"
#define	string_sameNode		"DialupMgr:109" FS "Cannot install an icon for your own system!"
#define	string_noAccessPortDir	"DialupMgr:100" FS "Unable to create \".port\" folder for storing modem defaults."
#define	string_installFailed	"DialupMgr:111" FS "Installation of \"%s\" failed!"
#define	string_noSelect		"DialupMgr:112" FS "You have not selected anything!"
#define	string_fopenWrite	"DialupMgr:113" FS "Failed to open %s for writing."
#define	string_updated		"DialupMgr:114" FS "Systems List saved."
#define	string_deleteConfirm	"DialupMgr:115" FS "Delete %s.  Are you sure?"
#define	string_noAccessNodeDir	"DialupMgr:116" FS "Could not create folder under '/var/spool/uucppublic'."
#define	string_noItem		"DialupMgr:117" FS "There are no items in this window."
#define	string_installDone	"DialupMgr:118" FS "Installation of \"%s\" done."
#define	string_noMultiple	"DialupMgr:119" FS "Can only install one system at a time."
#define	string_pathDeny		"DialupMgr:120" FS "\"%s\" path does not exist or permission to access is denied."
#define	string_pathExist	"DialupMgr:121" FS "\"%s\" already exist!"
#define	string_longFilename	"DialupMgr:122" FS "\"%s\" is too long!  Must be 14 characters or less."
#define	string_notFound		"DialupMgr:123" FS "System specified not in the list!"
#define	string_blankPhone	"DialupMgr:124" FS "You must provide a phone number!"
#define	string_invalidChar	"DialupMgr:125" FS "Invalid character: '%c'."
#define	string_exceed58		"DialupMgr:126" FS "Phone number can not exceed 58 digits!"
#define	string_connectFail	"DialupMgr:127" FS "Connect failed."
#define	string_lostConnect	"DialupMgr:128" FS "Lost Connect."
#define	string_lostCarrier	"DialupMgr:129" FS "Lost Carrier."
#define	string_dialFail		"DialupMgr:130" FS "Dial failed."
#define	string_scriptFail	"DialupMgr:131" FS "Caller script failed."
#define	string_noDevice		"DialupMgr:132" FS "Device not available."
#define	string_noSystem		"DialupMgr:133" FS "System not in the system list."
#define	string_unknownFail	"DialupMgr:134" FS "Connect failed for unknown reason."
#define	string_startCU		"DialupMgr:135" FS "Calling ..."
#define	string_deviceFail	"DialupMgr:136" FS "Device failed."
#define	string_itemNotSave	"DialupMgr:137" FS "Current entry changes not saved..."
#define	string_startRFT		"DialupMgr:138" FS "Copying ..."
#define	string_badSystem	"DialupMgr:139" FS "Destination system name is invalid."
#define	string_badFile 		"DialupMgr:140" FS "Can not get file(s) status."
#define	string_badFileName	"DialupMgr:141" FS "File(s) to be transferred has invalid filename(s)."
#define	string_folderDeny	"DialupMgr:142" FS "Can not read the folder."
#define	string_folderEmpty	"DialupMgr:143" FS "Folder empty!"
#define	string_partialFail	"DialupMgr:144" FS "Request  partially completed.  An error report will be sent to you via mail."
#define	string_killedCU		"DialupMgr:145" FS "cu terminated by a kill signal."
#define	string_forkFail		"DialupMgr:146" FS "Can not create a new process."
#define	string_usageCU		"DialupMgr:147" FS "Half duplex mode and Odd parity can not be specified at the same time."
#define	string_openFail		"DialupMgr:148" FS "Can't open %s."
#define	string_accessFail	"DialupMgr:149" FS "Can't access %s."
#define	string_writeFail	"DialupMgr:150" FS "Can't write to %s."
#define	string_createFail	"DialupMgr:151" FS "Can't create %s."
#define string_header		"DialupMgr:152" FS "System        Speed   Phone       "
#define	string_saved		"DialupMgr:153" FS "Devices Item saved."
#define	string_noFile		"DialupMgr:154" FS "'%s' does not exist and you are not authorized to create it!"
#define	string_unKnown		"DialupMgr:155" FS "%f is unkown.  Check the Address entry for %f in the Internet Setup or Dialup Setup icons."

#define	label_actions		"DialupMgr:210" FS "Actions"
#define	label_msystem		"DialupMgr:211" FS "System"
#define	label_mdevice		"DialupMgr:212" FS "Device"
#define	label_search		"DialupMgr:213" FS "Search"
#define	label_devices		"DialupMgr:214" FS "Setup Devices..."
#define	label_mdial		"DialupMgr:215" FS "Quick Dial..."
#define	label_dial		"DialupMgr:216" FS "Dial"
#define	label_install		"DialupMgr:217" FS "Install..."
#define	label_minstall		"DialupMgr:218" FS "Install"
#define	label_location		"DialupMgr:219" FS "Location:"
#define	label_help		"DialupMgr:220" FS "Help"
#define	label_save		"DialupMgr:221" FS "Save Systems List"
#define	label_open		"DialupMgr:222" FS "Open"
#define	label_exit		"DialupMgr:223" FS "Exit"
#define	label_discard		"DialupMgr:224" FS "Discard"
#define	label_add		"DialupMgr:225" FS "Add"
#define	label_new		"DialupMgr:226" FS "New..."
#define	label_delete		"DialupMgr:227" FS "Delete"
#define	label_cancel		"DialupMgr:228" FS "Cancel"
#define	label_mfind		"DialupMgr:229" FS "Find..."
#define	label_find		"DialupMgr:230" FS "Find"
#define	label_first		"DialupMgr:231" FS "First"
#define	label_last		"DialupMgr:232" FS "Last"
#define	label_continue		"DialupMgr:233" FS "Continue"
#define	label_autocall		"DialupMgr:234" FS "AutoCall"
#define	label_properties	"DialupMgr:235" FS "Properties..."
#define	label_apply		"DialupMgr:236" FS "Apply"
#define	label_reset		"DialupMgr:237" FS "Reset"
#define	label_com1		"DialupMgr:238" FS "Com1"
#define	label_com2		"DialupMgr:239" FS "Com2"
#define	label_other		"DialupMgr:240" FS "Other"
#define	label_type		"DialupMgr:241" FS "Type:"
#define	label_name		"DialupMgr:242" FS "Name:"
#define	label_port		"DialupMgr:243" FS "Port:"
#define	label_modemType		"DialupMgr:244" FS "Device Type:"
#define	label_speed		"DialupMgr:245" FS "Speed:"
#define	label_system		"DialupMgr:246" FS "System Name:"
#define	label_destination	"DialupMgr:247" FS "Destination:"
#define	label_class		"DialupMgr:248" FS "Speed:"
#define	label_phone		"DialupMgr:249" FS "Phone Number:"
#define	label_login		"DialupMgr:250" FS "Login ID:"
#define	label_password		"DialupMgr:251" FS "Password:"
#define	label_loginSeq1		"DialupMgr:252" FS "Login Sequence (1):"
#define	label_loginSeq2		"DialupMgr:253" FS "Login Sequence (2):"
#define	label_phoneOrName	"DialupMgr:254" FS "Phone Number:"
#define	label_parity		"DialupMgr:255" FS "Parity:"
#define	label_duplex		"DialupMgr:256" FS "Duplex Mode:"
#define	label_full		"DialupMgr:257" FS "Full"
#define	label_half		"DialupMgr:258" FS "Half"
#define	label_stopBits		"DialupMgr:259" FS "Stop Bits:"
#define	label_charSize		"DialupMgr:260" FS "Character Size:"
#define	label_direct		"DialupMgr:261" FS "Direct"
#define	label_datakit		"DialupMgr:262" FS "Datakit"
#define	label_penril		"DialupMgr:263" FS "Penril"
#define	label_ventel		"DialupMgr:264" FS "Ventel"
#define	label_hayes		"DialupMgr:265" FS "Hayes"
#define	label_hayesSM1200	"DialupMgr:266" FS "HayesSmart 1200"
#define	label_hayesSM2400	"DialupMgr:267" FS "HayesSmart 2400"
#define	label_att4000		"DialupMgr:268" FS "AT&T 4000"
#define	label_att4024		"DialupMgr:269" FS "AT&T 4024"
#define	label_att2224		"DialupMgr:270" FS "AT&T DATAPHONE 2224"
#define	label_att2248		"DialupMgr:271" FS "AT&T DATAPHONE 2248"
#define	label_att2296		"DialupMgr:272" FS "AT&T DATAPHONE 2296"
#define	label_tb		"DialupMgr:273" FS "Trailblazer"
#define	label_multitech		"DialupMgr:274" FS "MultiTech"
#define	label_any		"DialupMgr:275" FS "Any"
#define	label_b300		"DialupMgr:276" FS "300"
#define	label_b1200		"DialupMgr:277" FS "1200"
#define	label_b2400		"DialupMgr:278" FS "2400"
#define	label_b4800		"DialupMgr:279" FS "4800"
#define	label_b9600		"DialupMgr:280" FS "9600"
#define	label_b19200		"DialupMgr:281" FS "19200"
#define	label_b38400		"DialupMgr:282" FS "38400"
#define	label_even		"DialupMgr:283" FS "Even"
#define	label_odd		"DialupMgr:284" FS "Odd"
#define	label_none		"DialupMgr:285" FS "None"
#define	label_one		"DialupMgr:286" FS "1"
#define	label_two		"DialupMgr:287" FS "2"
#define	label_seven		"DialupMgr:288" FS "7"
#define	label_eight		"DialupMgr:289" FS "8"
#define	label_setup		"DialupMgr:290" FS "Dialup Setup ..."
#define	label_toc		"DialupMgr:291" FS "Table of Contents ..."
#define	label_desk		"DialupMgr:292" FS "Help Desk ..."
#define	label_send		"DialupMgr:293" FS "Send"
#define	label_modem		"DialupMgr:294" FS "Modem"
#define	label_uucp		"DialupMgr:295" FS "UUCP"
#define	label_inet		"DialupMgr:296" FS "Internet"
#define	label_extra		"DialupMgr:297" FS "Extra Option?"
#define	label_quitWarn		"DialupMgr:298" FS "Quit Warning"

#define	mnemonic_actions	"DialupMgr:410" FS "A"
#define	mnemonic_msystem	"DialupMgr:411" FS "S"
#define	mnemonic_mdevice	"DialupMgr:412" FS "D"
#define	mnemonic_search		"DialupMgr:413" FS "r"
#define	mnemonic_devices	"DialupMgr:414" FS "D"
#define	mnemonic_mdial		"DialupMgr:415" FS "l"
#define	mnemonic_dial		"DialupMgr:416" FS "D"
#define	mnemonic_install	"DialupMgr:417" FS "I"
#define	mnemonic_minstall	"DialupMgr:418" FS "I"
#define	mnemonic_help		"DialupMgr:419" FS "H"
#define	mnemonic_save		"DialupMgr:420" FS "S"
#define	mnemonic_open		"DialupMgr:421" FS "O"
#define	mnemonic_exit		"DialupMgr:422" FS "X"
#define	mnemonic_discard	"DialupMgr:423" FS "D"
#define	mnemonic_add		"DialupMgr:424" FS "A"
#define	mnemonic_new		"DialupMgr:425" FS "N"
#define	mnemonic_delete		"DialupMgr:426" FS "D"
#define	mnemonic_cancel		"DialupMgr:427" FS "C"
#define	mnemonic_mfind		"DialupMgr:428" FS "F"
#define	mnemonic_find		"DialupMgr:429" FS "F"
#define	mnemonic_continue	"DialupMgr:430" FS "C"
#define	mnemonic_autocall	"DialupMgr:431" FS "A"
#define	mnemonic_direct		"DialupMgr:432" FS "D"
#define	mnemonic_properties	"DialupMgr:433" FS "P"
#define	mnemonic_first		"DialupMgr:434" FS "i"
#define	mnemonic_last		"DialupMgr:435" FS "L"
#define	mnemonic_apply		"DialupMgr:436" FS "A"
#define	mnemonic_reset		"DialupMgr:437" FS "R"
#define	mnemonic_setup		"DialupMgr:438" FS "D"
#define	mnemonic_toc		"DialupMgr:439" FS "T"
#define	mnemonic_desk		"DialupMgr:440" FS "H"
#define	mnemonic_any		"DialupMgr:441" FS "A"
#define	mnemonic_b300		"DialupMgr:442" FS "x"
#define	mnemonic_b1200		"DialupMgr:443" FS "1"
#define	mnemonic_b2400		"DialupMgr:444" FS "2"
#define	mnemonic_b4800		"DialupMgr:445" FS "4"
#define	mnemonic_b9600		"DialupMgr:446" FS "9"
#define	mnemonic_b19200		"DialupMgr:447" FS "0"
#define	mnemonic_b38400		"DialupMgr:448" FS "3"
#define	mnemonic_even		"DialupMgr:449" FS "E"
#define	mnemonic_odd		"DialupMgr:450" FS "O"
#define	mnemonic_none		"DialupMgr:451" FS "N"
#define	mnemonic_seven		"DialupMgr:452" FS "7"
#define	mnemonic_eight		"DialupMgr:453" FS "8"
#define	mnemonic_full		"DialupMgr:454" FS "F"
#define	mnemonic_half		"DialupMgr:455" FS "l"
#define	mnemonic_send		"DialupMgr:456" FS "S"
#define	mnemonic_datakit	"DialupMgr:457" FS "k"
#define	mnemonic_modem	 	"DialupMgr:458" FS "M"
#define	mnemonic_uucp		"DialupMgr:459" FS "U"
#define	mnemonic_inet		"DialupMgr:460" FS "I"


#define	help_setup		"DialupMgr:500" FS "10"
#define	help_dsetup		"DialupMgr:501" FS "200"
#define	help_dial		"DialupMgr:502" FS "330"
#define	help_find		"DialupMgr:503" FS "150"
#define	help_install		"DialupMgr:504" FS "60"
#define	help_property		"DialupMgr:505" FS "430"
#define	help_dproperty		"DialupMgr:506" FS "380"
#define	help_toc		"DialupMgr:507" FS "180"
#define	help_desk		"DialupMgr:508" FS "190"
#define	help_dinstall		"DialupMgr:510" FS "230"
#define	help_dtcall		"DialupMgr:580" FS "10"
#define	help_remote		"DialupMgr:590" FS "10"

#define	title_install		"DialupMgr:600" FS "Install Remote System Icon"
#define	title_properties	"DialupMgr:601" FS "Remote System Properties"
#define	title_dproperties	"DialupMgr:602" FS "Device Properties"
#define	title_devices		"DialupMgr:603" FS "Devices"
#define	title_setup		"DialupMgr:604" FS "Dialup Setup"
#define	title_dial		"DialupMgr:605" FS "Quick Dial"
#define	title_find		"DialupMgr:606" FS "Find"
#define	title_hinstall		"DialupMgr:607" FS "Install"
#define	title_property		"DialupMgr:608" FS "Properties"
#define	title_toc		"DialupMgr:609" FS "Table of Contents"
#define	title_remote		"DialupMgr:610" FS "Remote System"
#define	title_deleteDev		"DialupMgr:611" FS "Delete Device"
#define	title_deleteSys		"DialupMgr:612" FS "Delete System"
#define	title_supportDev	"DialupMgr:613" FS "Device Type List"

#endif /* __Ol_Dialup_Error_h__ */
