/*	Copyright (c) 1990, 1991, 1992 UNIX System Laboratories, Inc.	*/
/*	Copyright (c) 1988, 1990 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF     	*/
/*	UNIX System Laboratories, Inc.                     	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ifndef	_DIALOG_SHP
#define	_DIALOG_SHP
#ident	"@(#)debugger:libol/common/Dialog_shP.h	1.2"

// toolkit specific members of the Dialog_shell class
// included by ../../gui.d/common/Dialog_sh.h

private:
	Widget		popup_window;	// primary widget - widget (in base class)
					// is form or rubber tile containing children
	Widget		control_area;	// widget containing buttons
	Widget		msg_widget;	// static text widget for error messages
	Widget		busy_widget;	// non-zero while executing a command
	Boolean		is_open;
	Boolean		ok_to_popdown;	// true if button pushed makes the dialog
					// go away when done
	int		cmds_sent;	// dialog can't popped down until debug cmds
					// are completed
	int		errors;		// number of errors generated by last action
	char		*error_string;	// BUFSIZ space for error messages
	void		*buttons;
	int		nbuttons;

public:
	void		make_buttons(const Button *, int num_buttons);

			// access functions
	Widget		get_popup_window()	{ return popup_window; }
	int		get_cmds_sent()		{ return cmds_sent; }
	void		set_ok_to_popdown(Boolean b) { ok_to_popdown = b; }
	void		set_is_open(Boolean b)	{ is_open = b; }

#endif	// _DIALOG_SHP
