/*	Copyright (c) 1990, 1991, 1992 UNIX System Laboratories, Inc.	*/
/*	Copyright (c) 1988, 1990 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF     	*/
/*	UNIX System Laboratories, Inc.                     	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ifndef	_WINDOW_SHP_H
#define _WINDOW_SHP_H
#ident	"@(#)debugger:libol/common/Window_shP.h	1.1"

// toolkit specific members of the Window_shell class
// included by ../../gui.d/common/Window_sh.h

private:
	int		busy_count;
	Component	*focus;
	Widget		window_widget;	// primary widget, widget in base class
					// is form widget
	Widget		msg_widget;	// static text widget for messages in footer
	char		*string;	// text displayed in footer
	int		errors;		// number of errors generated by last action


#endif // WINDOW_SHP_H
