#	Copyright (c) 1990, 1991, 1992 UNIX System Laboratories, Inc.
#	Copyright (c) 1988, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)debugger:libmachine/i386/makefile	1.1"

include $(CMDRULES)

TARGET = $(PRODLIB)/libmachine.a

include ../../util/common/std.make

CCSOURCES = \
	Instr.C

CSOURCES = \
	Tables.c

include DEPEND

include ../../util/common/lib.make
