.\"ident	"@(#)dtm:olwsm/olwsm.man	1.3"

.TH OLWSM 1 "12/1/89" "OPEN LOOK 2.0"
.SH NAME
olwsm - OPEN LOOK Workspace Manager
.SH SYNOPSIS
.B olwsm
.SH DESCRIPTION
.B olwsm
is the AT&T workspace manager embodying the look and feel of OPEN LOOK.
.P
.br
.SH "SEE ALSO"
X(1),
olwm(1),
olfm(1)
.SH COPYRIGHT
Copyright 1989, AT&T
