.\"ident	"@(#)r5fontutil:clients/bdftosnf/bdftosnf.man	1.1"
.TH BDFTOSNF 1 "Release 4" "X Version 11"
.SH NAME
bdftosnf - BDF to SNF font compiler for X11
.SH SYNOPSIS
.B "bdftosnf"
[-s] [-p#] [-u#] [-m] [-l] [-M] [-L] [-w] [-W] [-t] [-i] [bdf-file]
.SH DESCRIPTION
.PP
.B bdftosnf
reads a Bitmap Distribution Format (BDF) font from the
specified file (or from standard input if no file is specified)
and writes an X11 server normal font (SNF) to standard output.
.SH OPTIONS
.TP 8
.B \-s
Force byte swapping. This should always be used on the 6386 and 730X.
.TP 8
.B \-p#
Force the glyph padding to a specific number.  The legal
values are 1, 2, 4, and 8.
.TP 8
.B \-u#
Force the scanline unit padding to a specific number.  The legal
values are 1, 2, and 4.
.TP 8
.B \-m
Force the bit order to most significant bit first.
.TP 8
.B \-l
Force the bit order to least significant bit first.
.TP 8
.B \-M
Force the byte order to most significant byte first.
.TP 8
.B \-L
Force the byte order to least significant byte first.
.TP 8
.B \-w
Print warnings if the character bitmaps have bits set to
one outside of their defined widths.
.TP 8
.B \-W
Print warnings for characters with an encoding of -1; the default is
to silently ignore such characters.
.TP 8
.B \-t
Expand glyphs in "terminal-emulator" fonts to fill the bounding box.
.TP 8
.B \-i
Don't compute correct ink metrics for "terminal-emulator" fonts.
.SH "SEE ALSO"
X(1), Xserver(1)
.br
"Bitmap Distribution Format 2.1"
