#!/usr/bin/sh
#ident	"@(#)bnu:uuto	2.8.2.4"
#ident "$Header: uuto 1.1 91/02/28 $"

uuto () {
f=""
d=""
error="0"
#	get file names
#	files must be readable,
#	directories must be readable/searchable
#	otherwise increment error count and skip it.
while test $#  -ge 1
do
	if test -d "$1" -a {"$1" = "." -o "$1" = ".."}
		then shift; continue
	elif test -r "$1" -a -f "$1"
		then f="$f $1"
	elif test -r "$1" -a -x "$1" -a -d "$1"
		then d="$d $1"
	else error=`expr 0$error + 1`
		if test -f "$1"
			then echo "uuto: <$UUP$1>: cannot read file" >&2
		elif test -d "$1"
			then echo "uuto: <$UUP$1>: directory not readable/searchable" >&2
		else
			echo "uuto: <$UUP$1>: file/directory not found" >&2
		fi
	fi
	shift
done
if test -n "$d" -a -n "$user"
then
	for i in $d
	do
		( cd $i; UUP="$UUP$i/"
		uuto * $1)
		error=`expr 0$error + 0$?`
	done
fi

if test -n "$f" -a -n "$user"
then
	uucp $a $f $remote!~/receive/$user/$mysys/$UUP

	if test "$?" != "0"
	then
		error=`expr 0$error + 01`
	fi
fi

return $error
}

# main uuto shell

export IFS PATH
IFS=" 	
"
PATH="/usr/bin"

a=""
temp=""
sub=""
mysys=`uuname -l`
mesg="uuto: usage: uuto [-m -p] files remote!user"
sigmsg="uuto: received signal"
if test  $# -lt 1
	then
		echo $mesg >&2
		exit 26
fi
trap "echo $sigmsg '<1>' >&2; exit 29" 1
trap "echo $sigmsg '<2>' >&2; exit 29" 2
trap "echo $sigmsg '<3>' >&2; exit 29" 3
trap "echo $sigmsg '<13>' >&2; exit 29" 13
trap "echo $sigmsg '<15>' >&2; exit 29" 15
copy=0
#	get options
while true
do
	case $1 in
	 -m)	a="$a $1" sub="$sub -m" ;;
	 -p)	a="$a -C" sub="$sub -p" copy=1 ;;
	 -w)	a="$a -w";;
	 -*)	echo $mesg >&2; exit 26;;
	 *)	break ;;
	esac
	shift
done
#	be sure have both files and destination
if test $# -eq 1
then
	echo $mesg >&2
	exit 26
fi
#	skip file names to get to destination
while test $#  -gt 1
do
	temp="$temp $1"
	shift
done
#	the recipient arg: remote!user
#	remote may be omitted (default is this machine)
#	must have at least !user
remote=`expr $1 : '\(.*\)!'`
user=`expr $1 : '.*!\(.*\)'`
if test -z "$user"
then
	echo "uuto: incomplete destination -- must specify user" >&2
	exit 27
fi
a="$a -d -n$user"

UUP=""
uuto $temp

if test "$error" != "0"
then
	echo "uuto: failed with <$error> error(s)" >&2
	exit 28
fi
