#	Copyright (c) 1990, 1991, 1992 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#	Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)chown:chown.mk	1.4.6.2"
#ident "$Header: chown.mk 1.2 91/03/21 $"

#		PROPRIETARY NOTICE (Combined)
#
#This source code is unpublished proprietary information
#constituting, or derived under license from AT&T's UNIX(r) System V.
#In addition, portions of such source code were derived from Berkeley
#4.3 BSD under license from the Regents of the University of
#California.
#
#
#
#		Copyright Notice 
#
#Notice of copyright on this source code product does not indicate 
#publication.
#
#	(c) 1986,1987,1988,1989  Sun Microsystems, Inc
#	(c) 1983,1984,1985,1986,1987,1988,1989  AT&T.
#	          All rights reserved.


#	Makefile for chown	

include $(CMDRULES)

INSDIR = $(USRBIN)
OWN = bin
GRP = bin

INCSYS = $(INC)

#top#
# Generated by makefile 1.47

MAKEFILE = chown.mk


MAINS = chown

OBJECTS =  chown.o

SOURCES =  chown.c

all:		$(MAINS)

chown:		chown.o	
	$(CC) -o chown  chown.o $(LDFLAGS) $(LDLIBS) $(SHLIBS)


chown.o:	 $(INC)/stdio.h $(INC)/ctype.h \
		 $(INCSYS)/sys/types.h $(INCSYS)/sys/stat.h \
		 $(INC)/dirent.h \
		 $(INC)/pwd.h $(INC)/unistd.h $(INC)/priv.h \
		 $(INC)/locale.h $(INC)/pfmt.h $(INC)/errno.h \
		 $(INC)/string.h


GLOBALINCS = $(INC)/ctype.h $(INC)/pwd.h $(INC)/stdio.h \
	$(INCSYS)/sys/stat.h $(INCSYS)/sys/types.h \
	$(INC)/dirent.h $(INC)/unistd.h $(INC)/priv.h \
	$(INC)/locale.h $(INC)/pfmt.h $(INC)/errno.h \
	$(INC)/string.h


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

install: all
	$(INS) -f $(INSDIR) -m 0555 -u $(OWN) -g $(GRP) $(MAINS)

size: all
	$(SIZE) $(MAINS)

strip: all
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(INSDIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(INSDIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
