#	Copyright (c) 1990, 1991, 1992 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#ident	"@(#)date:common/cmd/date/date.mk	1.1.14.2"
#ident "$Header: date.mk 1.3 91/04/08 $"

#	Makefile for date 

include $(CMDRULES)

INSDIR = $(USRBIN)
OWN = bin
GRP = bin

#top#
# Generated by makefile 1.47

MAKEFILE = date.mk

MAINS = date

OBJECTS =  date.o

SOURCES =  date.c

all:		$(MAINS)

date:		date.o 
	$(CC) -o $@ date.o $(LDFLAGS) $(LDLIBS) $(PERFLIBS)

date.o:		$(INC)/sys/types.h $(INC)/utmp.h $(INC)/sys/uadmin.h \
		$(INC)/stdio.h $(INC)/time.h $(INC)/priv.h \
		$(INC)/pfmt.h $(INC)/errno.h $(INC)/string.h

GLOBALINCS = 	$(INC)/sys/types.h $(INC)/utmp.h $(INC)/sys/uadmin.h \
		$(INC)/stdio.h $(INC)/time.h $(INC)/priv.h \
		$(INC)/pfmt.h $(INC)/errno.h $(INC)/string.h

clean:
	rm -f $(OBJECTS)

clobber: clean
	rm -f $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

install: all
	$(INS) -f $(INSDIR) -m 0555 -u $(OWN) -g $(GRP) $(MAINS)

size: all
	$(SIZE) $(MAINS)

strip: all
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(INSDIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(INSDIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
