.\"ident	"@(#)olam:olam.man	1.2"
.TH OLAM 1 "21 December 1988" "OPEN LOOK(tm) 1.0"
.SH NAME
olam - OPEN LOOK(tm) Administration Manager
.SH SYNOPSIS
.B olam &
.SH DESCRIPTION
\fIolam\fP is the OPEN LOOK Administration Manager client.
.PP
.SH EXAMPLES
olam &
.PP
.SH "Files"
/etc/X0.hosts
/usr/X/lib/Xconnections
.PP
.SH "SEE ALSO"
OPENLOOK(1)
.SH COPYRIGHT
Copyright 1988, AT&T
.br
See \fIOPENLOOK(1)\fP for a full statement of rights and permissions.
.SH AUTHOR
Jeff Prem, AT&T
