/*	Copyright (c) 1990, 1991, 1992 UNIX System Laboratories, Inc.	*/
/*	Copyright (c) 1988, 1989, 1990 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF     	*/
/*	UNIX System Laboratories, Inc.                     	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ifndef	NOIDENT
#ident	"@(#)xterm:VTparse.h	1.14"
#endif
/*
 VTparse.h (C hdr file)
	Acc: 601052189 Tue Jan 17 09:56:29 1989
	Mod: 601054000 Tue Jan 17 10:26:40 1989
	Sta: 601054000 Tue Jan 17 10:26:40 1989
	Owner: 7007
	Group: 1985
	Permissions: 666
*/
/*
	START USER STAMP AREA
*/
/*
	END USER STAMP AREA
*/

/* Copyright 1987 by Digital Equipment Corporation, Maynard, Massachusetts. */

#include <X11/copyright.h>

#define	CASE_GROUND_STATE	0
#define	CASE_IGNORE_STATE	(CASE_GROUND_STATE+1)
#define	CASE_IGNORE_ESC		(CASE_IGNORE_STATE+1)
#define	CASE_IGNORE		(CASE_IGNORE_ESC+1)
#define	CASE_BELL		(CASE_IGNORE+1)
#define	CASE_BS			(CASE_BELL+1)
#define	CASE_CR			(CASE_BS+1)
#define	CASE_ESC		(CASE_CR+1)
#define	CASE_VMOT		(CASE_ESC+1)
#define	CASE_TAB		(CASE_VMOT+1)
#define	CASE_SI			(CASE_TAB+1)
#define	CASE_SO			(CASE_SI+1)
#define	CASE_SCR_STATE		(CASE_SO+1)
#define	CASE_SCS0_STATE		(CASE_SCR_STATE+1)
#define	CASE_SCS1_STATE		(CASE_SCS0_STATE+1)
#define	CASE_SCS2_STATE		(CASE_SCS1_STATE+1)
#define	CASE_SCS3_STATE		(CASE_SCS2_STATE+1)
#define	CASE_ESC_IGNORE		(CASE_SCS3_STATE+1)
#define	CASE_ESC_DIGIT		(CASE_ESC_IGNORE+1)
#define	CASE_ESC_SEMI		(CASE_ESC_DIGIT+1)
#define	CASE_DEC_STATE		(CASE_ESC_SEMI+1)
#define	CASE_ICH		(CASE_DEC_STATE+1)
#define	CASE_CUU		(CASE_ICH+1)
#define	CASE_CUD		(CASE_CUU+1)
#define	CASE_CUF		(CASE_CUD+1)
#define	CASE_CUB		(CASE_CUF+1)
#define	CASE_CUP		(CASE_CUB+1)
#define	CASE_ED			(CASE_CUP+1)
#define	CASE_EL			(CASE_ED+1)
#define	CASE_IL			(CASE_EL+1)
#define	CASE_DL			(CASE_IL+1)
#define	CASE_DCH		(CASE_DL+1)
#define	CASE_DA1		(CASE_DCH+1)
#define	CASE_TRACK_MOUSE	(CASE_DA1+1)
#define	CASE_TBC		(CASE_TRACK_MOUSE+1)
#define	CASE_SET		(CASE_TBC+1)
#define	CASE_RST		(CASE_SET+1)
#define	CASE_SGR		(CASE_RST+1)
#define	CASE_CPR		(CASE_SGR+1)
#define	CASE_DECSTBM		(CASE_CPR+1)
#define	CASE_DECREQTPARM	(CASE_DECSTBM+1)
#define	CASE_DECSET		(CASE_DECREQTPARM+1)
#define	CASE_DECRST             (CASE_DECSET+1)
#define	CASE_DECALN		(CASE_DECRST+1)
#define	CASE_GSETS		(CASE_DECALN+1)
#define	CASE_DECSC		(CASE_GSETS+1)
#define	CASE_DECRC		(CASE_DECSC+1)
#define	CASE_IND		(CASE_DECRC+1)
#define	CASE_NEL		(CASE_IND+1)
#define	CASE_HTS		(CASE_NEL+1)
#define	CASE_RI			(CASE_HTS+1)
#define	CASE_SS2		(CASE_RI+1)
#define	CASE_SS3		(CASE_SS2+1)
#define	CASE_CSI_STATE		(CASE_SS3+1)
#define	CASE_OSC		(CASE_CSI_STATE+1)
#define	CASE_RIS		(CASE_OSC+1)
#define	CASE_LS2		(CASE_RIS+1)
#define	CASE_LS3		(CASE_LS2+1)
#define	CASE_LS3R		(CASE_LS3+1)
#define	CASE_LS2R		(CASE_LS3R+1)
#define	CASE_LS1R		(CASE_LS2R+1)
#define	CASE_PRINT		(CASE_LS1R+1)
#define	CASE_XTERM_SAVE		(CASE_PRINT+1)
#define	CASE_XTERM_RESTORE	(CASE_XTERM_SAVE+1)
#define	CASE_XTERM_TITLE	(CASE_XTERM_RESTORE+1)
/* SS-mouse */
#define	CASE_GET_MOUSE		(CASE_XTERM_TITLE+1)
#define	CASE_REQ_MOUSE_POS	(CASE_GET_MOUSE+1)
/* SS-end-mouse */
/* EHR3 - AT&T STATES */
#define	CASE_INCURSES_STATE	(CASE_REQ_MOUSE_POS+1)
#define	CASE_OUTCURSES_STATE	(CASE_INCURSES_STATE+1)
#define	CASE_ATT_STATE		(CASE_OUTCURSES_STATE+1)
#define	CASE_IOCTLRECV_STATE		(CASE_ATT_STATE+1)
#define	CASE_IOCTLREPLY_STATE		(CASE_IOCTLRECV_STATE+1)
#define	CASE_KDDISPTYPE_STATE		(CASE_IOCTLREPLY_STATE+1)
#define	CASE_KDGKBENT_STATE		(CASE_KDDISPTYPE_STATE+1)
#define	CASE_KDSKBENT_STATE		(CASE_KDGKBENT_STATE+1)
#define	CASE_KDGKBMODE_STATE		(CASE_KDSKBENT_STATE+1)
#define	CASE_KDSKBMODE_STATE		(CASE_KDGKBMODE_STATE+1)
#define	CASE_GIO_ATTR_STATE		(CASE_KDSKBMODE_STATE+1)
#define	CASE_GIO_COLOR_STATE		(CASE_GIO_ATTR_STATE+1)
#define	CASE_GIO_KEYMAP_STATE		(CASE_GIO_COLOR_STATE+1)
#define	CASE_PIO_KEYMAP_STATE		(CASE_GIO_KEYMAP_STATE+1)
#define	CASE_GIO_STRMAP_STATE		(CASE_PIO_KEYMAP_STATE+1)
#define	CASE_PIO_STRMAP_STATE		(CASE_GIO_STRMAP_STATE+1)
#define	CASE_GETFKEY_STATE		(CASE_PIO_STRMAP_STATE+1)
#define	CASE_SETFKEY_STATE		(CASE_GETFKEY_STATE+1)
#define	CASE_SW_B40X25_STATE		(CASE_SETFKEY_STATE+1)
#define	CASE_SW_C40X25_STATE		(CASE_SW_B40X25_STATE+1)
#define	CASE_SW_B80X25_STATE		(CASE_SW_C40X25_STATE+1)
#define	CASE_SW_C80X25_STATE		(CASE_SW_B80X25_STATE+1)
#define	CASE_SW_EGAMONO80X25_STATE	(CASE_SW_C80X25_STATE+1)
#define	CASE_SW_ENHB40X25_STATE		(CASE_SW_EGAMONO80X25_STATE+1)
#define	CASE_SW_ENHC40X25_STATE		(CASE_SW_ENHB40X25_STATE+1)
#define	CASE_SW_ENHB80X25_STATE		(CASE_SW_ENHC40X25_STATE+1)
#define	CASE_SW_ENHC80X25_STATE		(CASE_SW_ENHB80X25_STATE+1)
#define	CASE_SW_ENHB80X43_STATE		(CASE_SW_ENHC80X25_STATE+1)
#define	CASE_SW_ENHC80X43_STATE		(CASE_SW_ENHB80X43_STATE+1)
#define	CASE_SW_MCAMODE_STATE		(CASE_SW_ENHC80X43_STATE+1)
#define	CASE_CONS_CURRENT_STATE		(CASE_SW_MCAMODE_STATE+1)
#define	CASE_CONS_GET_STATE		(CASE_CONS_CURRENT_STATE+1)
#define	CASE_TIOCVTNAME_STATE		(CASE_CONS_GET_STATE+1)
#define	CASE_GIO_SCRNMAP_STATE		(CASE_TIOCVTNAME_STATE+1)
#define	CASE_PIO_SCRNMAP_STATE		(CASE_GIO_SCRNMAP_STATE+1)
/* EHR3 - END AT&T STATES */
